[package]
name = "makcu"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9.2"
serialport = { version = "4.7.2", default-features = false }
thiserror = "2.0.12"
tokio = { version = "1.47.1", features = ["full"] }
tracing = "0.1.41"
